### ISSUE TITLE
Clarify the configuration options

### ISSUE THREAD

**Issue by SivartMcDorf** [TheMrMilchmann/TheFenceUnleashed#3]
recommend better documentation of the settings and what they do.  I tried to install this on my server and had to add Minecraft:player to the allow list for me to get through gates, then I added other entities and they couldn't pass through.  I wasn't sure what the allow, block, check meant for the settings.  I had to disable it from my server until I can figure out the settings and how to make it work.  Recommend adding the default animals from Minecraft automatically be blocked and the player to be automatically allowed.

**Comment by TheMrMilchmann** [comment]
I originally planned to document the configuration options but never got around to doing that, so you have a point. However, I'm not sure what is happening in your case specifically.

If this is the only mod you are using, you shouldn't have to touch the configuration at all. If you are using other mods, you might have to add some entities to the allow-/blocklist manually. To understand why, let me explain the settings:

The allowlist and blocklist are straightforward. Entities in these lists are always allowed to or blocked from passing through fence gates. If an entity is not in either of those lists, the `defaultBehavior` is used. The three values for the default behavior are:
- `ALLOW`, to allow passthrough,
- `BLOCK`, to block passthrough, and
- `CHECK`, to check whether an entity should be able to pass through on a best-effort basis.

The `CHECK` behavior typically only blocks animal-like entities from passing through and works perfectly with vanilla mobs. However, it might not correctly identify some modded entities (e.g. [MineColonies' citizens](https://github.com/TheMrMilchmann/TheFenceUnleashed/issues/2)).

**Comment by SivartMcDorf** [comment]
I had to add Minecraft:player then I added minecolonies:citizen.  That
didn't work for the npc so I removed those and tried the block function,
that didn't work so I added back the allow and then tried to change it to
check.  No matter what I did the minecolonies npc was either blocked or
only certain ones could pass.

**Comment by SivartMcDorf** [comment]
It would make sense that only leashable entities should be blocked.
Otherwise if they can't be leashed there is no way to get them through.

**Comment by TheMrMilchmann** [comment]
Please paste your full config file and the versions of The Fence Unleashed and MinecraftForge.

**Comment by SivartMcDorf** [comment]
Thanks, we can't upgrade to 18.2 without starting the world over so we are kind of stuck.
